version: '3.9'
services:  
  backend:
    build:
      context: ./trackmylifts-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  
  frontend:
    build:
      context: ./trackmylifts-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend